/// Flutter icons ForwaredArrow
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ForwaredArrow
///      fonts:
///       - asset: fonts/ForwaredArrow.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ForwaredArrow {
  ForwaredArrow._();

  static const _kFontFam = 'ForwaredArrow';
  static const _kFontPkg = null;

  static const IconData right_arrow = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
