/// Flutter icons GoogleIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GoogleIcon
///      fonts:
///       - asset: fonts/GoogleIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GoogleIcon {
  GoogleIcon._();

  static const _kFontFam = 'GoogleIcon';
  static const _kFontPkg = null;

  static const IconData icons8_google = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
