/// Flutter icons Rarow
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Rarow
///      fonts:
///       - asset: fonts/Rarow.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Rarow {
  Rarow._();

  static const _kFontFam = 'Rarow';
  static const String _kFontPkg = null;

  static const IconData right_arrow__1_ =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
